### ISSUE TITLE
Mortal Kombat Deadly Alliance / Tournament Edition via gPSP (specifically the PocketGo V1)

### ISSUE THREAD

**Issue by MysteryMan3D** [fleroviux/gba-bios#11]
I wanna be able to play Mortal Kombat Deadly Alliance and Mortal Kombat Tournament Edition for GBA on my PocketGo V1, which uses gPSP. Both games freeze at the Midway logo, but I know they can run because I've played them on another gPSP for CFW on the Super Retrocade with no issues.

I ran both of them on RetroArch's gPSP core and, just like on the PocketGo, they freeze at the Midway logo, so we can use that emulator as testing ground.

Using Normatt's open-source BIOS, as well as your BIOS the way it is now, was what was causing the games to freeze. Once I swapped it out with the official BIOS, both games ran perfectly.

But I don't wanna have to hunt down a GBA or DS Lite and the tools I need to dump my own copy of the official BIOS, because it'd be prohibitively expensive. I don't wanna use a pirated BIOS either because I don't like illegally downloading.

Please try to fix this issue for me so I can use your BIOS to run the games on my PocketGo with no issues. It'd be greatly appreciated and will save me money and frustration.

**Comment by DenSinH** [comment]
Looking into it a little now, it seems Mortal Kombat Tournament Edition is stuck in RLUncompWrite8Bit.

The first time it is called, it gets the "Size of decompressed data" argument wrong (it ends up below zero), though I don't think this causes the issue.

**Comment by DenSinH** [comment]
Actually, it no longer seems stuck, I just thought it wouldn't take as long. That is, on the version in #13

**Comment by DenSinH** [comment]
It's not stuck on the master version either, so I am going to close this issue. You just need to wait for a (fairly long) while.
