### ISSUE TITLE
Oversight in reset_modes routine

### ISSUE THREAD

**Issue by ladystarbreeze** [fleroviux/gba-bios#2]
The reset_modes routine in entrypoint.s unconditionally switches to System mode before branching to the address in the link register. However, the routine is reused to reset registers on cold boot; since  the CPU has never been in System mode by the time this function is called, the value of the System mode link register is undefined and the BIOS will crash.

**Comment by fleroviux** [comment]
Fixed in https://github.com/Cult-of-GBA/BIOS/commit/32bf0990f6de1807a875f81538f4fe49f20465cf
